### PR TITLE
New York Times Article Page Clone

### PR DESCRIPTION
**Pull request by Davidosky007**
##New York Times Article Page Clone

In this project, my partner and I explored the different positioning skills ranging from inline-block, floats, position, flex, and grid. We gained a deeper understanding of how to position and properly layout elements on the page. We combined these different methods to achieve our goals by reproducing the clone of the New York Times Article page.

One of our major challenges in this project was aligning the thumbnail images into the various grids in the "The Theory of Inflation" section.

In the course of the project, we learned and mastered the use of advanced CSS selectors which we used in styling most of the elements.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team,

**Good job on your project. Your attention to detail is remarkable.**

**Before your project is approved, please make the following changes:**

1). **Ensure the editor's pick section matches the styling of the original page.**

original  | clone
--------- | --------
editor_original |  editors_clone

2). **For your readme file:**

- **add a screenshot of your webpage above the 'built with' title.**

- **Fix the issues page link.**

**Happy coding!**

**PS: You can reach me on slack(Rose Wanjohi)**

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

#### Hello @Naqhid and @Davidosky007, Great job! 👏  

Both of you have done so well on this project, I am impressed, the sprite image under *Theory of inflation* 👍 , good one. The effective use of `flex`, `grid`, and `float`. Well done guys 👏 👏 

Let us quickly add some finishing touches and request another review.

- [ ] Fix the HTML validation warnings/errors, use the [w3 Validator](https://validator.w3.org/)

- [ ] Your PR (pull request) descriptions are good, but update the PR title to a more meaningful one

- [ ] Update the image preview in your ReadMe file to a better one, this is what I am seeing: 
Screen Shot 2020-09-27 at 8 46 34 AM

- [ ] Your Editor's Pick section can still be improved upon  [OPTIONAL] 
editors_pick

#### Make these changes and you should be good to go 😄 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning:

### Hello team :wave: 

**A lot has been done in this project. I must commend your efforts in fixing the changes as required by the previous reviewers. However, there are still more changes to be made.**

- I believe there's a layout issue in the `other articles` section of the page. See the images below:

Source page: 


Your clone:


- In this same section from the original page, the title of the listed articles are not dark grey but black.

Source page:


Your clone:


- This is also applicable to the `Most Popular` articles section.

Source page


Your clone: 


Please make these changes and request another review when you're done.

I'm @taofeekolalere on slack.
Happy coding :man_technologist:

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

I see you've implemented most of the changes requested. Make this change and request another review, then you should be good.

Fix your PR title:
pr

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

Hi, @Naqhid and @Davidosky007 congratulations on completing your project and taking the time to implement all the changes requested. 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by teekaytech — COMMENTED** [review]
### Status :Invalid Review Request :heavy_multiplication_x: 

**Hi team, congratulations on submitting your first code review request. Unfortunately, I cannot review your project.**

* * *
- [ ] **You submitted a wrong pull request for this project.**
- This project is titled 'Forms` but you submitted a PR for the `New York Times` project.


### Please note that this Code Review Request will be marked as invalid, so please submit a new one once you are ready!

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
